/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package br.unipar.atv_0703;

import java.awt.event.KeyEvent;
import javax.swing.JOptionPane;

/**
 *
 * @author vwaz
 */
public class CalcularMedia extends javax.swing.JPanel {

    /**
     * Creates new form CalcularMedia
     */
    public CalcularMedia() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tfNota4 = new javax.swing.JTextField();
        tfNota2 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        tfNota1 = new javax.swing.JTextField();
        tfNota3 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        tfNota4.setName("tfNota4"); // NOI18N
        tfNota4.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tfNota4KeyReleased(evt);
            }
        });

        tfNota2.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        tfNota2.setName("tfNota2"); // NOI18N
        tfNota2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfNota2ActionPerformed(evt);
            }
        });
        tfNota2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tfNota2KeyReleased(evt);
            }
        });

        jLabel4.setText("Nota 2");

        jLabel1.setText("Nota 1");

        tfNota1.setName("tfNota1"); // NOI18N
        tfNota1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tfNota1KeyReleased(evt);
            }
        });

        tfNota3.setName("tfNota3"); // NOI18N
        tfNota3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfNota3ActionPerformed(evt);
            }
        });
        tfNota3.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tfNota3KeyReleased(evt);
            }
        });

        jLabel2.setText("Nota 3");

        jLabel3.setText("Nota 4");

        jButton1.setText("Calcular Média");
        jButton1.setAlignmentY(0.0F);
        jButton1.setName("btCalcular"); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jButton1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jButton1KeyReleased(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, 380, Short.MAX_VALUE)
                .addGap(14, 14, 14))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(tfNota1)
                    .addComponent(tfNota3))
                .addGap(80, 80, 80)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel4)
                    .addComponent(jLabel3)
                    .addComponent(tfNota4)
                    .addComponent(tfNota2))
                .addGap(91, 91, 91))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfNota1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfNota2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfNota3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfNota4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(79, 79, 79)
                .addComponent(jButton1)
                .addGap(26, 26, 26))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void tfNota2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfNota2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfNota2ActionPerformed

    private void tfNota3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfNota3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfNota3ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        calcularMedia();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jButton1KeyReleased
        if(evt.getKeyCode()==KeyEvent.VK_ENTER){
            calcularMedia();
        }
    }//GEN-LAST:event_jButton1KeyReleased

    private void tfNota4KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfNota4KeyReleased
        if(evt.getKeyCode()==KeyEvent.VK_ENTER){
            calcularMedia();
        }
    }//GEN-LAST:event_tfNota4KeyReleased

    private void tfNota1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfNota1KeyReleased
       if(evt.getKeyCode()==KeyEvent.VK_ENTER){
            calcularMedia();
        }
    }//GEN-LAST:event_tfNota1KeyReleased

    private void tfNota3KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfNota3KeyReleased
        if(evt.getKeyCode()==KeyEvent.VK_ENTER){
            calcularMedia();
        }
    }//GEN-LAST:event_tfNota3KeyReleased

    private void tfNota2KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfNota2KeyReleased
        if(evt.getKeyCode()==KeyEvent.VK_ENTER){
            calcularMedia();
        }
    }//GEN-LAST:event_tfNota2KeyReleased


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextField tfNota1;
    private javax.swing.JTextField tfNota2;
    private javax.swing.JTextField tfNota3;
    private javax.swing.JTextField tfNota4;
    // End of variables declaration//GEN-END:variables
    private void calcularMedia() {
        int lista[] = new int[4];
        double media = 0;
        lista[0]= Integer.parseInt(tfNota1.getText());
        lista[1]= Integer.parseInt(tfNota2.getText());
        lista[2]= Integer.parseInt(tfNota3.getText());
        lista[3]= Integer.parseInt(tfNota4.getText());
      
        for(int i = 0; i<lista.length;i++){
            media +=lista[i]; 
        }
        media = media/4;
        JOptionPane.showMessageDialog(null, "Sua média foi:" + media);
    }

}
