/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package br.unipar.atv_0703;

import java.awt.event.KeyEvent;
import javax.swing.JOptionPane;

/**
 *
 * @author vwaz
 */
public class TextDemo extends javax.swing.JPanel {

    /**
     * Creates new form TextDemo
     */
    public TextDemo() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tfTexto = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        taTexto = new javax.swing.JTextArea();

        tfTexto.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                tfTextoFocusLost(evt);
            }
        });
        tfTexto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfTextoActionPerformed(evt);
            }
        });
        tfTexto.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tfTextoKeyReleased(evt);
            }
        });

        taTexto.setColumns(20);
        taTexto.setRows(5);
        jScrollPane1.setViewportView(taTexto);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(76, 76, 76)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1)
                    .addComponent(tfTexto))
                .addContainerGap(90, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(tfTexto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(44, 44, 44)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(127, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void tfTextoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tfTextoFocusLost
      
    }//GEN-LAST:event_tfTextoFocusLost

    private void tfTextoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfTextoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfTextoActionPerformed

    private void tfTextoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfTextoKeyReleased
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
            taTexto.append(tfTexto.getText() + "\n");
        if(tfTexto.getText().toUpperCase().equals("VERDE")){
            JOptionPane.showMessageDialog(null, "Você quis dizer ovos verde?");
        }else if( tfTexto.getText().toUpperCase().equals("TESTE")){
            String options = "Ok";
            
            JOptionPane.showOptionDialog(null, 
                    "Teste em Produção", 
                    "Teste", 
                    JOptionPane.YES_OPTION, 
                    JOptionPane.QUESTION_MESSAGE, 
                    null, 
                    null, 
                    options);
        }else if(tfTexto.getText().toUpperCase().equals("BATATINHA")){
            Object[] options = {"Sim", "Nem pensar", "Não entendi a referência"};
            int n;
            
            n = JOptionPane.showOptionDialog(null,
                    "Vamos jogar batatinha frita 123?", 
                    "Batatinha", 
                    JOptionPane.YES_NO_CANCEL_OPTION, 
                    JOptionPane.WARNING_MESSAGE, 
                    null, 
                    options, 
                    options[2]);
            if(n==0){
                taTexto.append(options[0].toString());
            }else if(n==1){
                taTexto.append(options[1].toString());
            }else{
                taTexto.append(options[2].toString());
            }
        }
        }
    }//GEN-LAST:event_tfTextoKeyReleased


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea taTexto;
    private javax.swing.JTextField tfTexto;
    // End of variables declaration//GEN-END:variables
}
